name: 'Republish LDES'
description: 'Replicates a Linked Data Event Stream or tree:Collection to your GitHub repository'
inputs:
  url:
    description: 'URL to LDES or tree:Collection dataset'
    required: true
  storage:
    description: 'Output directory name where the fetched data will be stored'
    required: true
  gh_pages_url:
    description: 'URL to the GitHub Pages repository'
    required: false
    default: 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/'
  gh_repository:
    description: 'Repository used to convert the data'
    required: false
    default: 'https://${{ github.repository_owner }}/${{ github.event.repository.name }}'
  git_username:
    description: 'Git username that makes the commits'
    required: false
    default: 'LDES-action'
  git_email:
    description: 'Git email that makes the commits'
    required: false
    default: 'LDES-action@users.noreply.github.com'
  literal_values:
    description: 'The different litteral values that need to be extracted and need to be divided and grouped in 24h'
    required: true
  url_feature_of_interest:
    description: 'url that defines the feature of interest of the observation'
    required: true
  url_timestamp:
    description: 'url that defines the timestamp'
    required: true
outputs:
  delta_bytes: # size of changed data
    description: 'The overall number of bytes changed in the output data this run (current size - previous size)'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Run main script
      run: node ${{ github.action_path }}/dist/index.js
      shell: bash
      env:
        INPUT_URL: ${{ inputs.url }}
        INPUT_STORAGE: ${{ inputs.storage }}
        INPUT_GH_PAGES_URL: ${{ inputs.gh_pages_url }}
        INPUT_GIT_USERNAME: ${{ inputs.git_username }}
        INPUT_GIT_EMAIL: ${{ inputs.git_email }}
        INPUT_LITERAL_VALUES: ${{ inputs.literal_values }}
        INPUT_URL_FEATURE_OF_INTEREST: ${{ inputs.url_feature_of_interest }}
        INPUT_URL_TIMESTAMP: ${{ inputs.url_timestamp }}
        INPUT_GH_REPOSITORY: ${{ inputs.gh_repository}}
    - name: Run post script
      run: node ${{ github.action_path }}/dist/post/index.js
      shell: bash
