# This is a basic workflow to help you get started with Actions

name: BlueBike

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: null

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  blueBike:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Fetch and write data blueBike
        uses: lucasderveaux/LinkedDataExtractor@main
        with:
          url: "https://www.pieter.pm/Blue-Bike-to-Linked-GBFS/root.ttl"
          storage: BB
          literal_values: '["https://w3id.org/gbfs#bikes_available", "https://w3id.org/gbfs#docks_in_use", "https://w3id.org/gbfs#capacity"]'
          url_timestamp: 'http://purl.org/dc/terms/created'
          url_feature_of_interest: 'http://purl.org/dc/terms/isVersionOf'
